//BC: USER HAS ALREADY SIGNED UP AND LOGGED IN. THIS PAGE WILL HAVE THE ADD/EDIT EVENT BUTTONS, SHOW THEIR EVENTS AND OTHER BY USER ZIPCODE (IF MULITPLE USERS HAVE THE SAME ZIPCODE THEY WILL SEE EACH OTHER'S EVENTS)

//http://localhost:3000/auth/userHomepage

/*
    -BUTTONS TO ADD/CRUD EVENTS
    -DISPLAY FIELD FOR ALL EVENTS WITH THEIR ZIPCODE

*/









